source 'http://rubygems.org'


gem 'rake'
gem 'thin'

gem 'rspec-core', '~>3.4.2'
gem 'rspec_junit_formatter', '0.2.2'
gem 'rspec-expectations', '~>3.4.0'
gem 'rspec-mocks'
gem 'rspec'
gem 'rantly'
gem 'sinatra', '~>1.4.7'
gem 'redis'
gem 'pry'
gem 'pg'
gem 'dm-timestamps'
gem 'dm-sqlite-adapter'
gem 'dm-postgres-adapter'
gem 'dm-mysql-adapter'
gem 'sinatra-contrib'
gem 'sinatra-cross_origin'
gem 'contracts'
gem 'mailgun-ruby'
gem 'data_mapper'
gem 'qiniu'